version: '3.5'

services:
  mkdocs:
    image: squidfunk/mkdocs-material:9.1
    container_name: kafka-docker
    restart: unless-stopped
    stop_grace_period: 1s
    ports:
      - "127.0.0.82:80:8000"
    volumes:
      - ./:/docs:ro
