apiVersion: v2
name: kafka
description:  Helm chart for Apache Kafka.
type: application

version: 13.2.0
appVersion: v3.5.1

maintainers:
  - name: sir5kong
    url: "https://github.com/sir5kong/kafka-docker"

keywords:
  - kafka
  - streaming
  - kraft
