exporter:
  enabled: true
  image:
    repository: danielqsj/kafka-exporter
    pullPolicy: IfNotPresent
    tag: v1.6.0
  ## exporter.podAnnotations
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9308"
    prometheus.io/scrape: "true"