image:
  repository: kafkace/kafka
  pullPolicy: IfNotPresent
  tag: v3.5.1

broker:
  ## broker.combinedMode, the server acts as both a broker and a controller.
  ## process.roles: "broker,controller"
  combinedMode:
    enabled: true
  replicaCount: 1
  heapOpts: "-Xms1024m -Xmx1024m"
  persistence:
    enabled: true
    size: 20Gi
    #storageClass: gp2
