ui:
  enabled: true
  image:
    repository: provectuslabs/kafka-ui
    pullPolicy: IfNotPresent
    # tag: v0.7.1

  ingress:
    enabled: true
    className: ""
    # annotations:
    #   nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16
    hosts:
      - host: kafka-ui.example.com
        #paths:
        #  - path: /
        #    pathType: ImplementationSpecific
    tls: []
    #  - secretName: kafka-example-tls
    #    hosts:
    #      - kafka-ui.example.com