image:
  repository: sir5kong/kafka
  pullPolicy: IfNotPresent
  tag: "3.3.2"

controller:
  replicaCount: 3
  heapOpts: "-Xms1024m -Xmx1024m"
  persistence:
    enabled: true
    size: 20Gi
    #storageClass: gp2
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi

broker:
  replicaCount: 3
  heapOpts: "-Xms4096m -Xmx4096m"
  persistence:
    enabled: true
    size: 50Gi
    #storageClass: gp2
  resources:
    limits:
      cpu: 4
      memory: 12Gi
    requests:
      cpu: 500m
      memory: 6Gi